-- H2 初始化脚本
-- 由 RuoYi 官方 MySQL 脚本转换而来，适用于 H2 2.x MySQL 兼容模式。
-- CREATE TABLE IF NOT EXISTS 与 MERGE 保证文件数据库重复启动时可安全执行。

-- RuoYi 系统表及初始数据
-- ----------------------------
-- 1、部门表
-- ----------------------------
create table if not exists sys_dept (
  dept_id           bigint      generated by default as identity,
  parent_id         bigint      default 0,
  ancestors         varchar(50)     default '',
  dept_name         varchar(30)     default '',
  order_num         int          default 0,
  leader            varchar(20)     default null,
  phone             varchar(11)     default null,
  email             varchar(50)     default null,
  status            char(1)         default '0',
  del_flag          char(1)         default '0',
  create_by         varchar(64)     default '',
  create_time 	    datetime,
  update_by         varchar(64)     default '',
  update_time       datetime,
  primary key (dept_id)
);

-- ----------------------------
-- 初始化-部门表数据。仅在记录不存在时写入，避免重启覆盖管理员在页面中的调整。
-- ----------------------------
insert into sys_dept select 100, 0,   '0',     '面料查询系统', 0, '', '', '', '0', '0', 'admin', current_timestamp, '', null
where not exists (select 1 from sys_dept where dept_id = 100);
insert into sys_dept select 101, 100, '0,100', '办公室',       1, '', '', '', '0', '0', 'admin', current_timestamp, '', null
where not exists (select 1 from sys_dept where dept_id = 101);
insert into sys_dept select 102, 100, '0,100', '开发部',       2, '', '', '', '0', '0', 'admin', current_timestamp, '', null
where not exists (select 1 from sys_dept where dept_id = 102);
insert into sys_dept select 103, 100, '0,100', '生产管理部',   3, '', '', '', '0', '0', 'admin', current_timestamp, '', null
where not exists (select 1 from sys_dept where dept_id = 103);
insert into sys_dept select 104, 100, '0,100', '业务部',       4, '', '', '', '0', '0', 'admin', current_timestamp, '', null
where not exists (select 1 from sys_dept where dept_id = 104);
insert into sys_dept select 105, 100, '0,100', '跟单部',       5, '', '', '', '0', '0', 'admin', current_timestamp, '', null
where not exists (select 1 from sys_dept where dept_id = 105);
insert into sys_dept select 106, 100, '0,100', '采购部',       6, '', '', '', '0', '0', 'admin', current_timestamp, '', null
where not exists (select 1 from sys_dept where dept_id = 106);
insert into sys_dept select 107, 100, '0,100', '裁床部',       7, '', '', '', '0', '0', 'admin', current_timestamp, '', null
where not exists (select 1 from sys_dept where dept_id = 107);
insert into sys_dept select 108, 100, '0,100', '版房',         8, '', '', '', '0', '0', 'admin', current_timestamp, '', null
where not exists (select 1 from sys_dept where dept_id = 108);


-- ----------------------------
-- 2、用户信息表
-- ----------------------------
create table if not exists sys_user (
  user_id           bigint      generated by default as identity,
  dept_id           bigint      default null,
  user_name         varchar(30)     not null,
  nick_name         varchar(30)     not null,
  user_type         varchar(2)      default '00',
  email             varchar(50)     default '',
  phonenumber       varchar(11)     default '',
  sex               char(1)         default '0',
  avatar            varchar(100)    default '',
  password          varchar(100)    default '',
  status            char(1)         default '0',
  del_flag          char(1)         default '0',
  login_ip          varchar(128)    default '',
  login_date        datetime,
  pwd_update_date   datetime,
  create_by         varchar(64)     default '',
  create_time       datetime,
  update_by         varchar(64)     default '',
  update_time       datetime,
  remark            varchar(500)    default null,
  primary key (user_id)
);

-- ----------------------------
-- 初始化-用户信息表数据
-- ----------------------------
merge into sys_user key(user_id) values(1,  101, 'admin', '系统管理员', '00', '', '', '0', '', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', '127.0.0.1', current_timestamp, current_timestamp, 'admin', current_timestamp, '', null, '系统管理员');
insert into sys_user (
  user_id, dept_id, user_name, nick_name, user_type, email, phonenumber, sex,
  avatar, password, status, del_flag, login_ip, login_date, pwd_update_date,
  create_by, create_time, update_by, update_time, remark
)
select 3, 103, 'fabric_manager', '面料主管', '00', '', '', '0',
       '', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2',
       '0', '0', '', null, null, 'admin', current_timestamp, '', null,
       '开发测试账号，初始密码 admin123，首次登录请修改'
where not exists (select 1 from sys_user where user_id = 3 or user_name = 'fabric_manager');
insert into sys_user (
  user_id, dept_id, user_name, nick_name, user_type, email, phonenumber, sex,
  avatar, password, status, del_flag, login_ip, login_date, pwd_update_date,
  create_by, create_time, update_by, update_time, remark
)
select 4, 104, 'fabric_entry', '面料录入员', '00', '', '', '0',
       '', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2',
       '0', '0', '', null, null, 'admin', current_timestamp, '', null,
       '开发测试账号，初始密码 admin123，首次登录请修改'
where not exists (select 1 from sys_user where user_id = 4 or user_name = 'fabric_entry');
insert into sys_user (
  user_id, dept_id, user_name, nick_name, user_type, email, phonenumber, sex,
  avatar, password, status, del_flag, login_ip, login_date, pwd_update_date,
  create_by, create_time, update_by, update_time, remark
)
select 5, 106, 'fabric_view', '面料查询员', '00', '', '', '0',
       '', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2',
       '0', '0', '', null, null, 'admin', current_timestamp, '', null,
       '开发测试账号，初始密码 admin123，首次登录请修改'
where not exists (select 1 from sys_user where user_id = 5 or user_name = 'fabric_view');


-- ----------------------------
-- 3、岗位信息表
-- ----------------------------
create table if not exists sys_post
(
  post_id       bigint      generated by default as identity,
  post_code     varchar(64)     not null,
  post_name     varchar(50)     not null,
  post_sort     int          not null,
  status        char(1)         not null,
  create_by     varchar(64)     default '',
  create_time   datetime,
  update_by     varchar(64)     default '',
  update_time   datetime,
  remark        varchar(500)    default null,
  primary key (post_id)
);

-- ----------------------------
-- 初始化-岗位信息表数据。岗位与部门分开维护，一个账号可关联多个岗位。
-- ----------------------------
insert into sys_post select 1, 'system_admin',       '系统管理员', 1,  '0', 'admin', current_timestamp, '', null, '负责账号、权限和系统配置'
where not exists (select 1 from sys_post where post_id = 1);
insert into sys_post select 2, 'dept_manager',       '部门负责人', 2,  '0', 'admin', current_timestamp, '', null, '负责部门业务与人员协作'
where not exists (select 1 from sys_post where post_id = 2);
insert into sys_post select 3, 'developer',          '开发专员',   3,  '0', 'admin', current_timestamp, '', null, '负责面料开发与资料整理'
where not exists (select 1 from sys_post where post_id = 3);
insert into sys_post select 4, 'office_clerk',       '办公室文员', 4,  '0', 'admin', current_timestamp, '', null, '负责日常行政与资料维护'
where not exists (select 1 from sys_post where post_id = 4);
insert into sys_post select 5, 'business_specialist','业务员',     5,  '0', 'admin', current_timestamp, '', null, '负责客户与面料业务'
where not exists (select 1 from sys_post where post_id = 5);
insert into sys_post select 6, 'merchandiser',       '跟单员',     6,  '0', 'admin', current_timestamp, '', null, '负责订单跟进与资料核对'
where not exists (select 1 from sys_post where post_id = 6);
insert into sys_post select 7, 'buyer',              '采购员',     7,  '0', 'admin', current_timestamp, '', null, '负责供应商与采购资料'
where not exists (select 1 from sys_post where post_id = 7);
insert into sys_post select 8, 'production_manager', '生产管理员', 8,  '0', 'admin', current_timestamp, '', null, '负责生产资料与进度管理'
where not exists (select 1 from sys_post where post_id = 8);
insert into sys_post select 9, 'cutter',             '裁床员',     9,  '0', 'admin', current_timestamp, '', null, '负责裁床相关工作'
where not exists (select 1 from sys_post where post_id = 9);
insert into sys_post select 10, 'pattern_maker',     '版房师傅',   10, '0', 'admin', current_timestamp, '', null, '负责版房与样版工作'
where not exists (select 1 from sys_post where post_id = 10);


-- ----------------------------
-- 4、角色信息表
-- ----------------------------
create table if not exists sys_role (
  role_id              bigint      generated by default as identity,
  role_name            varchar(30)     not null,
  role_key             varchar(100)    not null,
  role_sort            int          not null,
  data_scope           char(1)         default '1',
  menu_check_strictly  tinyint      default 1,
  dept_check_strictly  tinyint      default 1,
  status               char(1)         not null,
  del_flag             char(1)         default '0',
  create_by            varchar(64)     default '',
  create_time          datetime,
  update_by            varchar(64)     default '',
  update_time          datetime,
  remark               varchar(500)    default null,
  primary key (role_id)
);

-- ----------------------------
-- 初始化-角色信息表数据
-- ----------------------------
merge into sys_role key(role_id) values('1', '超级管理员',  'admin',  1, 1, 1, 1, '0', '0', 'admin', current_timestamp, '', null, '超级管理员');
merge into sys_role key(role_id) values('2', '系统维护员',  'system_maintainer', 2, 2, 1, 1, '0', '0', 'admin', current_timestamp, '', null, '开发与运行维护人员使用');
merge into sys_role key(role_id) values('3', '面料主管',    'fabric_manager', 3, 1, 1, 1, '0', '0', 'admin', current_timestamp, '', null, '管理全部面料档案，不含系统管理权限');
merge into sys_role key(role_id) values('4', '面料录入员',  'fabric_entry',   4, 1, 1, 1, '0', '0', 'admin', current_timestamp, '', null, '可查看全部面料，只能修改本人录入的面料');
merge into sys_role key(role_id) values('5', '面料查询员',  'fabric_view',    5, 1, 1, 1, '0', '0', 'admin', current_timestamp, '', null, '仅可查询面料档案');


-- ----------------------------
-- 5、菜单权限表
-- ----------------------------
create table if not exists sys_menu (
  menu_id           bigint      generated by default as identity,
  menu_name         varchar(50)     not null,
  parent_id         bigint      default 0,
  order_num         int          default 0,
  path              varchar(200)    default '',
  component         varchar(255)    default null,
  query             varchar(255)    default null,
  route_name        varchar(50)     default '',
  is_frame          int          default 1,
  is_cache          int          default 0,
  menu_type         char(1)         default '',
  visible           char(1)         default 0,
  status            char(1)         default 0,
  perms             varchar(100)    default null,
  icon              varchar(100)    default '#',
  create_by         varchar(64)     default '',
  create_time       datetime,
  update_by         varchar(64)     default '',
  update_time       datetime,
  remark            varchar(500)    default '',
  primary key (menu_id)
);

-- ----------------------------
-- 初始化-菜单信息表数据
-- ----------------------------
-- 一级菜单
merge into sys_menu key(menu_id) values('1', '账号与组织', '0', '10', 'system', null,         '', '', 1, 0, 'M', '0', '0', '', 'system',  'admin', current_timestamp, '', null, '账号、权限、部门和岗位管理');
merge into sys_menu key(menu_id) values('2', '运行维护',   '0', '20', 'monitor', null,        '', '', 1, 0, 'M', '0', '0', '', 'monitor', 'admin', current_timestamp, '', null, '管理员运行维护入口');
merge into sys_menu key(menu_id) values('3', '开发工具',   '0', '90', 'tool', null,           '', '', 1, 0, 'M', '1', '0', '', 'tool',    'admin', current_timestamp, '', null, '开发人员工具，默认不在侧边栏显示');
merge into sys_menu key(menu_id) values('4', '使用帮助',   '0', '30', 'help', 'help/index',   '', '', 1, 0, 'C', '0', '0', '', 'guide',   'admin', current_timestamp, '', null, '面料查询系统使用帮助');
-- 二级菜单
merge into sys_menu key(menu_id) values('100',  '账号管理', '1',   '1', 'user',       'system/user/index',        '', '', 1, 0, 'C', '0', '0', 'system:user:list',        'user',          'admin', current_timestamp, '', null, '系统账号管理');
merge into sys_menu key(menu_id) values('101',  '权限角色', '1',   '2', 'role',       'system/role/index',        '', '', 1, 0, 'C', '0', '0', 'system:role:list',        'peoples',       'admin', current_timestamp, '', null, '角色与菜单权限管理');
merge into sys_menu key(menu_id) values('102',  '菜单配置', '1',   '7', 'menu',       'system/menu/index',        '', '', 1, 0, 'C', '1', '0', 'system:menu:list',        'tree-table',    'admin', current_timestamp, '', null, '开发维护功能，默认隐藏');
merge into sys_menu key(menu_id) values('103',  '部门设置', '1',   '3', 'dept',       'system/dept/index',        '', '', 1, 0, 'C', '0', '0', 'system:dept:list',        'tree',          'admin', current_timestamp, '', null, '公司部门结构');
merge into sys_menu key(menu_id) values('104',  '岗位设置', '1',   '4', 'post',       'system/post/index',        '', '', 1, 0, 'C', '0', '0', 'system:post:list',        'post',          'admin', current_timestamp, '', null, '员工岗位设置');
merge into sys_menu key(menu_id) values('105',  '数据字典', '1',   '8', 'dict',       'system/dict/index',        '', '', 1, 0, 'C', '1', '0', 'system:dict:list',        'dict',          'admin', current_timestamp, '', null, '开发维护功能，默认隐藏');
merge into sys_menu key(menu_id) values('106',  '系统参数', '1',   '9', 'config',     'system/config/index',      '', '', 1, 0, 'C', '1', '0', 'system:config:list',      'edit',          'admin', current_timestamp, '', null, '开发维护功能，默认隐藏');
merge into sys_menu key(menu_id) values('107',  '通知公告', '1',   '5', 'notice',     'system/notice/index',      '', '', 1, 0, 'C', '0', '0', 'system:notice:list',      'message',       'admin', current_timestamp, '', null, '系统通知公告');
merge into sys_menu key(menu_id) values('108',  '操作记录', '1',   '6', 'log',        '',                         '', '', 1, 0, 'M', '0', '0', '',                        'log',           'admin', current_timestamp, '', null, '操作与登录记录');
merge into sys_menu key(menu_id) values('109',  '在线用户', '2',   '1', 'online',     'monitor/online/index',     '', '', 1, 0, 'C', '0', '0', 'monitor:online:list',     'online',        'admin', current_timestamp, '', null, '在线用户菜单');
merge into sys_menu key(menu_id) values('110',  '定时任务', '2',   '90', 'job',        'monitor/job/index',        '', '', 1, 0, 'C', '1', '0', 'monitor:job:list',        'job',           'admin', current_timestamp, '', null, '暂无业务任务，默认隐藏');
merge into sys_menu key(menu_id) values('111',  '数据监控', '2',   '91', 'druid',      'monitor/druid/index',      '', '', 1, 0, 'C', '1', '0', 'monitor:druid:list',      'druid',         'admin', current_timestamp, '', null, '开发维护功能，默认隐藏');
merge into sys_menu key(menu_id) values('112',  '服务监控', '2',   '2', 'server',     'monitor/server/index',     '', '', 1, 0, 'C', '0', '0', 'monitor:server:list',     'server',        'admin', current_timestamp, '', null, '服务监控菜单');
merge into sys_menu key(menu_id) values('113',  '缓存监控', '2',   '3', 'cache',      'monitor/cache/index',      '', '', 1, 0, 'C', '0', '0', 'monitor:cache:list',      'redis',         'admin', current_timestamp, '', null, '缓存监控菜单');
merge into sys_menu key(menu_id) values('114',  '缓存列表', '2',   '4', 'cacheList',  'monitor/cache/list',       '', '', 1, 0, 'C', '0', '0', 'monitor:cache:list',      'redis-list',    'admin', current_timestamp, '', null, '缓存明细');
merge into sys_menu key(menu_id) values('115',  '表单构建', '3',   '1', 'build',      'tool/build/index',         '', '', 1, 0, 'C', '0', '0', 'tool:build:list',         'build',         'admin', current_timestamp, '', null, '表单构建菜单');
merge into sys_menu key(menu_id) values('116',  '代码生成', '3',   '2', 'gen',        'tool/gen/index',           '', '', 1, 0, 'C', '0', '0', 'tool:gen:list',           'code',          'admin', current_timestamp, '', null, '代码生成菜单');
merge into sys_menu key(menu_id) values('117',  '系统接口', '3',   '3', 'swagger',    'tool/swagger/index',       '', '', 1, 0, 'C', '0', '0', 'tool:swagger:list',       'swagger',       'admin', current_timestamp, '', null, '系统接口菜单');
-- 三级菜单
merge into sys_menu key(menu_id) values('500',  '操作日志', '108', '1', 'operlog',    'monitor/operlog/index',    '', '', 1, 0, 'C', '0', '0', 'monitor:operlog:list',    'form',          'admin', current_timestamp, '', null, '操作日志菜单');
merge into sys_menu key(menu_id) values('501',  '登录日志', '108', '2', 'logininfor', 'monitor/logininfor/index', '', '', 1, 0, 'C', '0', '0', 'monitor:logininfor:list', 'logininfor',    'admin', current_timestamp, '', null, '登录日志菜单');
-- 用户管理按钮
merge into sys_menu key(menu_id) values('1000', '用户查询', '100', '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:query',          '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1001', '用户新增', '100', '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:add',            '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1002', '用户修改', '100', '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:edit',           '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1003', '用户删除', '100', '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:remove',         '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1004', '用户导出', '100', '5',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:export',         '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1005', '用户导入', '100', '6',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:import',         '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1006', '重置密码', '100', '7',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:resetPwd',       '#', 'admin', current_timestamp, '', null, '');
-- 角色管理按钮
merge into sys_menu key(menu_id) values('1007', '角色查询', '101', '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:query',          '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1008', '角色新增', '101', '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:add',            '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1009', '角色修改', '101', '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:edit',           '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1010', '角色删除', '101', '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:remove',         '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1011', '角色导出', '101', '5',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:export',         '#', 'admin', current_timestamp, '', null, '');
-- 菜单管理按钮
merge into sys_menu key(menu_id) values('1012', '菜单查询', '102', '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:query',          '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1013', '菜单新增', '102', '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:add',            '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1014', '菜单修改', '102', '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:edit',           '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1015', '菜单删除', '102', '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:remove',         '#', 'admin', current_timestamp, '', null, '');
-- 部门管理按钮
merge into sys_menu key(menu_id) values('1016', '部门查询', '103', '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:query',          '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1017', '部门新增', '103', '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:add',            '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1018', '部门修改', '103', '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:edit',           '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1019', '部门删除', '103', '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:remove',         '#', 'admin', current_timestamp, '', null, '');
-- 岗位管理按钮
merge into sys_menu key(menu_id) values('1020', '岗位查询', '104', '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:query',          '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1021', '岗位新增', '104', '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:add',            '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1022', '岗位修改', '104', '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:edit',           '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1023', '岗位删除', '104', '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:remove',         '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1024', '岗位导出', '104', '5',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:export',         '#', 'admin', current_timestamp, '', null, '');
-- 字典管理按钮
merge into sys_menu key(menu_id) values('1025', '字典查询', '105', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:query',          '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1026', '字典新增', '105', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:add',            '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1027', '字典修改', '105', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:edit',           '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1028', '字典删除', '105', '4', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:remove',         '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1029', '字典导出', '105', '5', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:export',         '#', 'admin', current_timestamp, '', null, '');
-- 参数设置按钮
merge into sys_menu key(menu_id) values('1030', '参数查询', '106', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:query',        '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1031', '参数新增', '106', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:add',          '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1032', '参数修改', '106', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:edit',         '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1033', '参数删除', '106', '4', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:remove',       '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1034', '参数导出', '106', '5', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:export',       '#', 'admin', current_timestamp, '', null, '');
-- 通知公告按钮
merge into sys_menu key(menu_id) values('1035', '公告查询', '107', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:query',        '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1036', '公告新增', '107', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:add',          '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1037', '公告修改', '107', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:edit',         '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1038', '公告删除', '107', '4', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:remove',       '#', 'admin', current_timestamp, '', null, '');
-- 操作日志按钮
merge into sys_menu key(menu_id) values('1039', '操作查询', '500', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:query',      '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1040', '操作删除', '500', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:remove',     '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1041', '日志导出', '500', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:export',     '#', 'admin', current_timestamp, '', null, '');
-- 登录日志按钮
merge into sys_menu key(menu_id) values('1042', '登录查询', '501', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:query',   '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1043', '登录删除', '501', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:remove',  '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1044', '日志导出', '501', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:export',  '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1045', '账户解锁', '501', '4', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:unlock',  '#', 'admin', current_timestamp, '', null, '');
-- 在线用户按钮
merge into sys_menu key(menu_id) values('1046', '在线查询', '109', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:query',       '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1047', '批量强退', '109', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:batchLogout', '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1048', '单条强退', '109', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:forceLogout', '#', 'admin', current_timestamp, '', null, '');
-- 定时任务按钮
merge into sys_menu key(menu_id) values('1049', '任务查询', '110', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:query',          '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1050', '任务新增', '110', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:add',            '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1051', '任务修改', '110', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:edit',           '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1052', '任务删除', '110', '4', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:remove',         '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1053', '状态修改', '110', '5', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:changeStatus',   '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1054', '任务导出', '110', '6', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:export',         '#', 'admin', current_timestamp, '', null, '');
-- 代码生成按钮
merge into sys_menu key(menu_id) values('1055', '生成查询', '116', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:query',             '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1056', '生成修改', '116', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:edit',              '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1057', '生成删除', '116', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:remove',            '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1058', '导入代码', '116', '4', '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:import',            '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1059', '预览代码', '116', '5', '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:preview',           '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('1060', '生成代码', '116', '6', '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:code',              '#', 'admin', current_timestamp, '', null, '');


-- ----------------------------
-- 6、用户和角色关联表  用户N-1角色
-- ----------------------------
create table if not exists sys_user_role (
  user_id   bigint not null,
  role_id   bigint not null,
  primary key(user_id, role_id)
);

-- ----------------------------
-- 初始化-用户和角色关联表数据
-- ----------------------------
merge into sys_user_role key(user_id, role_id) values ('1', '1');
merge into sys_user_role key(user_id, role_id) values ('3', '3');
merge into sys_user_role key(user_id, role_id) values ('4', '4');
merge into sys_user_role key(user_id, role_id) values ('5', '5');


-- ----------------------------
-- 7、角色和菜单关联表  角色1-N菜单
-- ----------------------------
create table if not exists sys_role_menu (
  role_id   bigint not null,
  menu_id   bigint not null,
  primary key(role_id, menu_id)
);

-- ----------------------------
-- 初始化-角色和菜单关联表数据
-- ----------------------------
merge into sys_role_menu key(role_id, menu_id) values ('2', '1');
merge into sys_role_menu key(role_id, menu_id) values ('2', '2');
merge into sys_role_menu key(role_id, menu_id) values ('2', '3');
merge into sys_role_menu key(role_id, menu_id) values ('2', '4');
merge into sys_role_menu key(role_id, menu_id) values ('2', '100');
merge into sys_role_menu key(role_id, menu_id) values ('2', '101');
merge into sys_role_menu key(role_id, menu_id) values ('2', '102');
merge into sys_role_menu key(role_id, menu_id) values ('2', '103');
merge into sys_role_menu key(role_id, menu_id) values ('2', '104');
merge into sys_role_menu key(role_id, menu_id) values ('2', '105');
merge into sys_role_menu key(role_id, menu_id) values ('2', '106');
merge into sys_role_menu key(role_id, menu_id) values ('2', '107');
merge into sys_role_menu key(role_id, menu_id) values ('2', '108');
merge into sys_role_menu key(role_id, menu_id) values ('2', '109');
merge into sys_role_menu key(role_id, menu_id) values ('2', '110');
merge into sys_role_menu key(role_id, menu_id) values ('2', '111');
merge into sys_role_menu key(role_id, menu_id) values ('2', '112');
merge into sys_role_menu key(role_id, menu_id) values ('2', '113');
merge into sys_role_menu key(role_id, menu_id) values ('2', '114');
merge into sys_role_menu key(role_id, menu_id) values ('2', '115');
merge into sys_role_menu key(role_id, menu_id) values ('2', '116');
merge into sys_role_menu key(role_id, menu_id) values ('2', '117');
merge into sys_role_menu key(role_id, menu_id) values ('2', '500');
merge into sys_role_menu key(role_id, menu_id) values ('2', '501');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1000');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1001');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1002');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1003');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1004');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1005');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1006');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1007');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1008');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1009');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1010');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1011');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1012');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1013');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1014');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1015');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1016');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1017');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1018');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1019');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1020');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1021');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1022');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1023');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1024');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1025');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1026');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1027');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1028');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1029');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1030');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1031');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1032');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1033');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1034');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1035');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1036');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1037');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1038');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1039');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1040');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1041');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1042');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1043');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1044');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1045');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1046');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1047');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1048');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1049');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1050');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1051');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1052');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1053');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1054');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1055');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1056');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1057');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1058');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1059');
merge into sys_role_menu key(role_id, menu_id) values ('2', '1060');

-- ----------------------------
-- 8、角色和部门关联表  角色1-N部门
-- ----------------------------
create table if not exists sys_role_dept (
  role_id   bigint not null,
  dept_id   bigint not null,
  primary key(role_id, dept_id)
);

-- ----------------------------
-- 初始化-角色和部门关联表数据
-- ----------------------------
merge into sys_role_dept key(role_id, dept_id) values ('2', '100');
merge into sys_role_dept key(role_id, dept_id) values ('2', '102');


-- ----------------------------
-- 9、用户与岗位关联表  用户1-N岗位
-- ----------------------------
create table if not exists sys_user_post
(
  user_id   bigint not null,
  post_id   bigint not null,
  primary key (user_id, post_id)
);

-- ----------------------------
-- 初始化-用户与岗位关联表数据
-- ----------------------------
merge into sys_user_post key(user_id, post_id) values ('1', '1');
merge into sys_user_post key(user_id, post_id) values ('3', '2');
merge into sys_user_post key(user_id, post_id) values ('3', '8');
merge into sys_user_post key(user_id, post_id) values ('4', '5');
merge into sys_user_post key(user_id, post_id) values ('5', '7');


-- ----------------------------
-- 10、操作日志记录
-- ----------------------------
create table if not exists sys_oper_log (
  oper_id           bigint      generated by default as identity,
  title             varchar(50)     default '',
  business_type     int          default 0,
  method            varchar(200)    default '',
  request_method    varchar(10)     default '',
  operator_type     int          default 0,
  oper_name         varchar(50)     default '',
  dept_name         varchar(50)     default '',
  oper_url          varchar(255)    default '',
  oper_ip           varchar(128)    default '',
  oper_location     varchar(255)    default '',
  oper_param        varchar(2000)   default '',
  json_result       varchar(2000)   default '',
  status            int          default 0,
  error_msg         varchar(2000)   default '',
  oper_time         datetime,
  cost_time         bigint      default 0,
  primary key (oper_id),
  index idx_sys_oper_log_bt (business_type),
  index idx_sys_oper_log_s (status),
  index idx_sys_oper_log_ot (oper_time)
);


-- ----------------------------
-- 11、字典类型表
-- ----------------------------
create table if not exists sys_dict_type
(
  dict_id          bigint      generated by default as identity,
  dict_name        varchar(100)    default '',
  dict_type        varchar(100)    default '',
  status           char(1)         default '0',
  create_by        varchar(64)     default '',
  create_time      datetime,
  update_by        varchar(64)     default '',
  update_time      datetime,
  remark           varchar(500)    default null,
  primary key (dict_id),
  constraint uk_sys_dict_type unique (dict_type)
);

merge into sys_dict_type key(dict_id) values(1,  '用户性别', 'sys_user_sex',        '0', 'admin', current_timestamp, '', null, '用户性别列表');
merge into sys_dict_type key(dict_id) values(2,  '菜单状态', 'sys_show_hide',       '0', 'admin', current_timestamp, '', null, '菜单状态列表');
merge into sys_dict_type key(dict_id) values(3,  '系统开关', 'sys_normal_disable',  '0', 'admin', current_timestamp, '', null, '系统开关列表');
merge into sys_dict_type key(dict_id) values(4,  '任务状态', 'sys_job_status',      '0', 'admin', current_timestamp, '', null, '任务状态列表');
merge into sys_dict_type key(dict_id) values(5,  '任务分组', 'sys_job_group',       '0', 'admin', current_timestamp, '', null, '任务分组列表');
merge into sys_dict_type key(dict_id) values(6,  '系统是否', 'sys_yes_no',          '0', 'admin', current_timestamp, '', null, '系统是否列表');
merge into sys_dict_type key(dict_id) values(7,  '通知类型', 'sys_notice_type',     '0', 'admin', current_timestamp, '', null, '通知类型列表');
merge into sys_dict_type key(dict_id) values(8,  '通知状态', 'sys_notice_status',   '0', 'admin', current_timestamp, '', null, '通知状态列表');
merge into sys_dict_type key(dict_id) values(9,  '操作类型', 'sys_oper_type',       '0', 'admin', current_timestamp, '', null, '操作类型列表');
merge into sys_dict_type key(dict_id) values(10, '系统状态', 'sys_common_status',   '0', 'admin', current_timestamp, '', null, '登录状态列表');


-- ----------------------------
-- 12、字典数据表
-- ----------------------------
create table if not exists sys_dict_data
(
  dict_code        bigint      generated by default as identity,
  dict_sort        int          default 0,
  dict_label       varchar(100)    default '',
  dict_value       varchar(100)    default '',
  dict_type        varchar(100)    default '',
  css_class        varchar(100)    default null,
  list_class       varchar(100)    default null,
  is_default       char(1)         default 'N',
  status           char(1)         default '0',
  create_by        varchar(64)     default '',
  create_time      datetime,
  update_by        varchar(64)     default '',
  update_time      datetime,
  remark           varchar(500)    default null,
  primary key (dict_code)
);

merge into sys_dict_data key(dict_code) values(1,  1,  '男',       '0',       'sys_user_sex',        '',   '',        'Y', '0', 'admin', current_timestamp, '', null, '性别男');
merge into sys_dict_data key(dict_code) values(2,  2,  '女',       '1',       'sys_user_sex',        '',   '',        'N', '0', 'admin', current_timestamp, '', null, '性别女');
merge into sys_dict_data key(dict_code) values(3,  3,  '未知',     '2',       'sys_user_sex',        '',   '',        'N', '0', 'admin', current_timestamp, '', null, '性别未知');
merge into sys_dict_data key(dict_code) values(4,  1,  '显示',     '0',       'sys_show_hide',       '',   'primary', 'Y', '0', 'admin', current_timestamp, '', null, '显示菜单');
merge into sys_dict_data key(dict_code) values(5,  2,  '隐藏',     '1',       'sys_show_hide',       '',   'danger',  'N', '0', 'admin', current_timestamp, '', null, '隐藏菜单');
merge into sys_dict_data key(dict_code) values(6,  1,  '正常',     '0',       'sys_normal_disable',  '',   'primary', 'Y', '0', 'admin', current_timestamp, '', null, '正常状态');
merge into sys_dict_data key(dict_code) values(7,  2,  '停用',     '1',       'sys_normal_disable',  '',   'danger',  'N', '0', 'admin', current_timestamp, '', null, '停用状态');
merge into sys_dict_data key(dict_code) values(8,  1,  '正常',     '0',       'sys_job_status',      '',   'primary', 'Y', '0', 'admin', current_timestamp, '', null, '正常状态');
merge into sys_dict_data key(dict_code) values(9,  2,  '暂停',     '1',       'sys_job_status',      '',   'danger',  'N', '0', 'admin', current_timestamp, '', null, '停用状态');
merge into sys_dict_data key(dict_code) values(10, 1,  '默认',     'DEFAULT', 'sys_job_group',       '',   '',        'Y', '0', 'admin', current_timestamp, '', null, '默认分组');
merge into sys_dict_data key(dict_code) values(11, 2,  '系统',     'SYSTEM',  'sys_job_group',       '',   '',        'N', '0', 'admin', current_timestamp, '', null, '系统分组');
merge into sys_dict_data key(dict_code) values(12, 1,  '是',       'Y',       'sys_yes_no',          '',   'primary', 'Y', '0', 'admin', current_timestamp, '', null, '系统默认是');
merge into sys_dict_data key(dict_code) values(13, 2,  '否',       'N',       'sys_yes_no',          '',   'danger',  'N', '0', 'admin', current_timestamp, '', null, '系统默认否');
merge into sys_dict_data key(dict_code) values(14, 1,  '通知',     '1',       'sys_notice_type',     '',   'warning', 'Y', '0', 'admin', current_timestamp, '', null, '通知');
merge into sys_dict_data key(dict_code) values(15, 2,  '公告',     '2',       'sys_notice_type',     '',   'success', 'N', '0', 'admin', current_timestamp, '', null, '公告');
merge into sys_dict_data key(dict_code) values(16, 1,  '正常',     '0',       'sys_notice_status',   '',   'primary', 'Y', '0', 'admin', current_timestamp, '', null, '正常状态');
merge into sys_dict_data key(dict_code) values(17, 2,  '关闭',     '1',       'sys_notice_status',   '',   'danger',  'N', '0', 'admin', current_timestamp, '', null, '关闭状态');
merge into sys_dict_data key(dict_code) values(18, 99, '其他',     '0',       'sys_oper_type',       '',   'info',    'N', '0', 'admin', current_timestamp, '', null, '其他操作');
merge into sys_dict_data key(dict_code) values(19, 1,  '新增',     '1',       'sys_oper_type',       '',   'info',    'N', '0', 'admin', current_timestamp, '', null, '新增操作');
merge into sys_dict_data key(dict_code) values(20, 2,  '修改',     '2',       'sys_oper_type',       '',   'info',    'N', '0', 'admin', current_timestamp, '', null, '修改操作');
merge into sys_dict_data key(dict_code) values(21, 3,  '删除',     '3',       'sys_oper_type',       '',   'danger',  'N', '0', 'admin', current_timestamp, '', null, '删除操作');
merge into sys_dict_data key(dict_code) values(22, 4,  '授权',     '4',       'sys_oper_type',       '',   'primary', 'N', '0', 'admin', current_timestamp, '', null, '授权操作');
merge into sys_dict_data key(dict_code) values(23, 5,  '导出',     '5',       'sys_oper_type',       '',   'warning', 'N', '0', 'admin', current_timestamp, '', null, '导出操作');
merge into sys_dict_data key(dict_code) values(24, 6,  '导入',     '6',       'sys_oper_type',       '',   'warning', 'N', '0', 'admin', current_timestamp, '', null, '导入操作');
merge into sys_dict_data key(dict_code) values(25, 7,  '强退',     '7',       'sys_oper_type',       '',   'danger',  'N', '0', 'admin', current_timestamp, '', null, '强退操作');
merge into sys_dict_data key(dict_code) values(26, 8,  '生成代码', '8',       'sys_oper_type',       '',   'warning', 'N', '0', 'admin', current_timestamp, '', null, '生成操作');
merge into sys_dict_data key(dict_code) values(27, 9,  '清空数据', '9',       'sys_oper_type',       '',   'danger',  'N', '0', 'admin', current_timestamp, '', null, '清空操作');
merge into sys_dict_data key(dict_code) values(28, 1,  '成功',     '0',       'sys_common_status',   '',   'primary', 'N', '0', 'admin', current_timestamp, '', null, '正常状态');
merge into sys_dict_data key(dict_code) values(29, 2,  '失败',     '1',       'sys_common_status',   '',   'danger',  'N', '0', 'admin', current_timestamp, '', null, '停用状态');


-- ----------------------------
-- 13、参数配置表
-- ----------------------------
create table if not exists sys_config (
  config_id         int          generated by default as identity,
  config_name       varchar(100)    default '',
  config_key        varchar(100)    default '',
  config_value      varchar(500)    default '',
  config_type       char(1)         default 'N',
  create_by         varchar(64)     default '',
  create_time       datetime,
  update_by         varchar(64)     default '',
  update_time       datetime,
  remark            varchar(500)    default null,
  primary key (config_id)
);

merge into sys_config key(config_id) values(1, '主框架页-默认皮肤样式名称',     'sys.index.skinName',               'skin-blue',     'Y', 'admin', current_timestamp, '', null, '蓝色 skin-blue、绿色 skin-green、紫色 skin-purple、红色 skin-red、黄色 skin-yellow' );
merge into sys_config key(config_id) values(2, '用户管理-账号初始密码',         'sys.user.initPassword',            'admin123',      'Y', 'admin', current_timestamp, '', null, '开发阶段初始化密码 admin123，首次登录后应修改' );
merge into sys_config key(config_id) values(3, '主框架页-侧边栏主题',           'sys.index.sideTheme',              'theme-dark',    'Y', 'admin', current_timestamp, '', null, '深色主题theme-dark，浅色主题theme-light' );
merge into sys_config key(config_id) values(4, '账号自助-验证码开关',           'sys.account.captchaEnabled',       'false',          'Y', 'admin', current_timestamp, '', null, '是否开启验证码功能（true开启，false关闭）');
merge into sys_config key(config_id) values(5, '账号自助-是否开启用户注册功能', 'sys.account.registerUser',         'false',         'Y', 'admin', current_timestamp, '', null, '是否开启注册用户功能（true开启，false关闭）');
merge into sys_config key(config_id) values(6, '用户登录-黑名单列表',           'sys.login.blackIPList',            '',              'Y', 'admin', current_timestamp, '', null, '设置登录IP黑名单限制，多个匹配项以;分隔，支持匹配（*通配、网段）');
merge into sys_config key(config_id) values(7, '用户管理-初始密码修改策略',     'sys.account.initPasswordModify',   '1',             'Y', 'admin', current_timestamp, '', null, '0：初始密码修改策略关闭，没有任何提示，1：提醒用户，如果未修改初始密码，则在登录时就会提醒修改密码对话框');
merge into sys_config key(config_id) values(8, '用户管理-账号密码更新周期',     'sys.account.passwordValidateDays', '0',             'Y', 'admin', current_timestamp, '', null, '密码更新周期（填写数字，数据初始化值为0不限制，若修改必须为大于0小于365的正整数），如果超过这个周期登录系统时，则在登录时就会提醒修改密码对话框');
merge into sys_config key(config_id) values(9, '用户管理-密码字符范围',         'sys.account.chrtype',              '0',             'Y', 'admin', current_timestamp, '', null, '默认任意字符范围，0任意（密码可以输入任意字符），1数字（密码只能为0-9数字），2英文字母（密码只能为a-z和A-Z字母），3字母和数字（密码必须包含字母，数字）,4字母数字和特殊字符（目前支持的特殊字符包括：~!@#$%^&*()-=_+）');


-- ----------------------------
-- 14、系统访问记录
-- ----------------------------
create table if not exists sys_logininfor (
  info_id        bigint     generated by default as identity,
  user_name      varchar(50)    default '',
  ipaddr         varchar(128)   default '',
  login_location varchar(255)   default '',
  browser        varchar(50)    default '',
  os             varchar(50)    default '',
  status         char(1)        default '0',
  msg            varchar(255)   default '',
  login_time     datetime,
  primary key (info_id),
  index idx_sys_logininfor_s (status),
  index idx_sys_logininfor_lt (login_time)
);


-- ----------------------------
-- 15、定时任务调度表
-- ----------------------------
create table if not exists sys_job (
  job_id              bigint    generated by default as identity,
  job_name            varchar(64)   default '',
  job_group           varchar(64)   default 'DEFAULT',
  invoke_target       varchar(500)  not null,
  cron_expression     varchar(255)  default '',
  misfire_policy      varchar(20)   default '3',
  concurrent          char(1)       default '1',
  status              char(1)       default '0',
  create_by           varchar(64)   default '',
  create_time         datetime,
  update_by           varchar(64)   default '',
  update_time         datetime,
  remark              varchar(500)  default '',
  primary key (job_id, job_name, job_group)
);

-- 不再初始化 RuoYi 演示定时任务，业务任务需要时由管理员创建。


-- ----------------------------
-- 16、定时任务调度日志表
-- ----------------------------
create table if not exists sys_job_log (
  job_log_id          bigint     generated by default as identity,
  job_name            varchar(64)    not null,
  job_group           varchar(64)    not null,
  invoke_target       varchar(500)   not null,
  job_message         varchar(500),
  status              char(1)        default '0',
  exception_info      varchar(2000)  default '',
  start_time          datetime,
  end_time            datetime,
  create_time         datetime,
  primary key (job_log_id)
);


-- ----------------------------
-- 17、通知公告表
-- ----------------------------
create table if not exists sys_notice (
  notice_id         int          generated by default as identity,
  notice_title      varchar(50)     not null,
  notice_type       char(1)         not null,
  notice_content    clob        default null,
  status            char(1)         default '0',
  create_by         varchar(64)     default '',
  create_time       datetime,
  update_by         varchar(64)     default '',
  update_time       datetime,
  remark            varchar(255)    default null,
  primary key (notice_id)
);

-- ----------------------------
-- 初始化-公告信息表数据
-- ----------------------------
merge into sys_notice key(notice_id) values('1', '面料查询系统已启用', '2', '<p>系统用于统一维护面料档案、实物图片、成分、分类和供应商资料。</p><p>请使用本人账号操作，不要多人共用管理员账号。</p>', '0', 'admin', current_timestamp, '', null, '系统说明');
merge into sys_notice key(notice_id) values('2', '面料录入规范', '1', '<p>新增面料前请核对分类、供应商、克重、门幅、成分比例、报价单位和实物图片。</p><p>系统自动生成入库日期和年度流水编号，请勿手工修改编号。</p>', '0', 'admin', current_timestamp, '', null, '业务规范');
merge into sys_notice key(notice_id) values('3', '账号权限说明', '1', '<p>面料主管可维护全部面料和基础资料；面料录入员可新增并修改本人录入的面料；面料查询员仅可查询。</p><p>账号、角色、部门和岗位由系统管理员维护。</p>', '0', 'admin', current_timestamp, '', null, '权限说明');


-- ----------------------------
-- 18、公告已读记录表
-- ----------------------------
create table if not exists sys_notice_read (
  read_id          bigint       generated by default as identity,
  notice_id        int           not null,
  user_id          bigint       not null,
  read_time        datetime         not null,
  primary key (read_id),
  constraint uk_user_notice unique (user_id, notice_id)
);


-- ----------------------------
-- 19、代码生成业务表
-- ----------------------------
create table if not exists gen_table (
  table_id          bigint      generated by default as identity,
  table_name        varchar(200)    default '',
  table_comment     varchar(500)    default '',
  sub_table_name    varchar(64)     default null,
  sub_table_fk_name varchar(64)     default null,
  class_name        varchar(100)    default '',
  tpl_category      varchar(200)    default 'crud',
  tpl_web_type      varchar(30)     default '',
  package_name      varchar(100),
  module_name       varchar(30),
  business_name     varchar(30),
  function_name     varchar(50),
  function_author   varchar(50),
  form_col_num      int          default 1,
  gen_type          char(1)         default '0',
  gen_path          varchar(200)    default '/',
  options           varchar(1000),
  create_by         varchar(64)     default '',
  create_time 	    datetime,
  update_by         varchar(64)     default '',
  update_time       datetime,
  remark            varchar(500)    default null,
  primary key (table_id)
);


-- ----------------------------
-- 20、代码生成业务表字段
-- ----------------------------
create table if not exists gen_table_column (
  column_id         bigint      generated by default as identity,
  table_id          bigint,
  column_name       varchar(200),
  column_comment    varchar(500),
  column_type       varchar(100),
  java_type         varchar(500),
  java_field        varchar(200),
  is_pk             char(1),
  is_increment      char(1),
  is_required       char(1),
  is_insert         char(1),
  is_edit           char(1),
  is_list           char(1),
  is_query          char(1),
  query_type        varchar(200)    default 'EQ',
  html_type         varchar(200),
  dict_type         varchar(200)    default '',
  sort              int,
  create_by         varchar(64)     default '',
  create_time 	    datetime,
  update_by         varchar(64)     default '',
  update_time       datetime,
  primary key (column_id)
);

-- Quartz 表
-- ----------------------------
-- 1、存储每一个已配置的 jobDetail 的详细信息
-- ----------------------------
create table if not exists QRTZ_JOB_DETAILS (
    sched_name           varchar(120)    not null,
    job_name             varchar(200)    not null,
    job_group            varchar(200)    not null,
    description          varchar(250)    null,
    job_class_name       varchar(250)    not null,
    is_durable           varchar(1)      not null,
    is_nonconcurrent     varchar(1)      not null,
    is_update_data       varchar(1)      not null,
    requests_recovery    varchar(1)      not null,
    job_data             blob            null,
    primary key (sched_name, job_name, job_group)
);

-- ----------------------------
-- 2、 存储已配置的 Trigger 的信息
-- ----------------------------
create table if not exists QRTZ_TRIGGERS (
    sched_name           varchar(120)    not null,
    trigger_name         varchar(200)    not null,
    trigger_group        varchar(200)    not null,
    job_name             varchar(200)    not null,
    job_group            varchar(200)    not null,
    description          varchar(250)    null,
    next_fire_time       bigint      null,
    prev_fire_time       bigint      null,
    priority             integer         null,
    trigger_state        varchar(16)     not null,
    trigger_type         varchar(8)      not null,
    start_time           bigint      not null,
    end_time             bigint      null,
    calendar_name        varchar(200)    null,
    misfire_instr        smallint     null,
    job_data             blob            null,
    primary key (sched_name, trigger_name, trigger_group),
    foreign key (sched_name, job_name, job_group) references QRTZ_JOB_DETAILS(sched_name, job_name, job_group)
);

-- ----------------------------
-- 3、 存储简单的 Trigger，包括重复次数，间隔，以及已触发的次数
-- ----------------------------
create table if not exists QRTZ_SIMPLE_TRIGGERS (
    sched_name           varchar(120)    not null,
    trigger_name         varchar(200)    not null,
    trigger_group        varchar(200)    not null,
    repeat_count         bigint       not null,
    repeat_interval      bigint      not null,
    times_triggered      bigint      not null,
    primary key (sched_name, trigger_name, trigger_group),
    foreign key (sched_name, trigger_name, trigger_group) references QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);

-- ----------------------------
-- 4、 存储 Cron Trigger，包括 Cron 表达式和时区信息
-- ----------------------------
create table if not exists QRTZ_CRON_TRIGGERS (
    sched_name           varchar(120)    not null,
    trigger_name         varchar(200)    not null,
    trigger_group        varchar(200)    not null,
    cron_expression      varchar(200)    not null,
    time_zone_id         varchar(80),
    primary key (sched_name, trigger_name, trigger_group),
    foreign key (sched_name, trigger_name, trigger_group) references QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);

-- ----------------------------
-- 5、 Trigger 作为 Blob 类型存储(用于 Quartz 用户用 JDBC 创建他们自己定制的 Trigger 类型，JobStore 并不知道如何存储实例的时候)
-- ----------------------------
create table if not exists QRTZ_BLOB_TRIGGERS (
    sched_name           varchar(120)    not null,
    trigger_name         varchar(200)    not null,
    trigger_group        varchar(200)    not null,
    blob_data            blob            null,
    primary key (sched_name, trigger_name, trigger_group),
    foreign key (sched_name, trigger_name, trigger_group) references QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);

-- ----------------------------
-- 6、 以 Blob 类型存储存放日历信息， quartz可配置一个日历来指定一个时间范围
-- ----------------------------
create table if not exists QRTZ_CALENDARS (
    sched_name           varchar(120)    not null,
    calendar_name        varchar(200)    not null,
    calendar             blob            not null,
    primary key (sched_name, calendar_name)
);

-- ----------------------------
-- 7、 存储已暂停的 Trigger 组的信息
-- ----------------------------
create table if not exists QRTZ_PAUSED_TRIGGER_GRPS (
    sched_name           varchar(120)    not null,
    trigger_group        varchar(200)    not null,
    primary key (sched_name, trigger_group)
);

-- ----------------------------
-- 8、 存储与已触发的 Trigger 相关的状态信息，以及相联 Job 的执行信息
-- ----------------------------
create table if not exists QRTZ_FIRED_TRIGGERS (
    sched_name           varchar(120)    not null,
    entry_id             varchar(95)     not null,
    trigger_name         varchar(200)    not null,
    trigger_group        varchar(200)    not null,
    instance_name        varchar(200)    not null,
    fired_time           bigint      not null,
    sched_time           bigint      not null,
    priority             integer         not null,
    state                varchar(16)     not null,
    job_name             varchar(200)    null,
    job_group            varchar(200)    null,
    is_nonconcurrent     varchar(1)      null,
    requests_recovery    varchar(1)      null,
    primary key (sched_name, entry_id)
);

-- ----------------------------
-- 9、 存储少量的有关 Scheduler 的状态信息，假如是用于集群中，可以看到其他的 Scheduler 实例
-- ----------------------------
create table if not exists QRTZ_SCHEDULER_STATE (
    sched_name           varchar(120)    not null,
    instance_name        varchar(200)    not null,
    last_checkin_time    bigint      not null,
    checkin_interval     bigint      not null,
    primary key (sched_name, instance_name)
);

-- ----------------------------
-- 10、 存储程序的悲观锁的信息(假如使用了悲观锁)
-- ----------------------------
create table if not exists QRTZ_LOCKS (
    sched_name           varchar(120)    not null,
    lock_name            varchar(40)     not null,
    primary key (sched_name, lock_name)
);

-- ----------------------------
-- 11、 Quartz集群实现同步机制的行锁表
-- ----------------------------
create table if not exists QRTZ_SIMPROP_TRIGGERS (
    sched_name           varchar(120)    not null,
    trigger_name         varchar(200)    not null,
    trigger_group        varchar(200)    not null,
    str_prop_1           varchar(512)    null,
    str_prop_2           varchar(512)    null,
    str_prop_3           varchar(512)    null,
    int_prop_1           int             null,
    int_prop_2           int             null,
    long_prop_1          bigint          null,
    long_prop_2          bigint          null,
    dec_prop_1           numeric(13,4)   null,
    dec_prop_2           numeric(13,4)   null,
    bool_prop_1          varchar(1)      null,
    bool_prop_2          varchar(1)      null,
    primary key (sched_name, trigger_name, trigger_group),
    foreign key (sched_name, trigger_name, trigger_group) references QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);

-- ----------------------------
-- 面料业务表
-- ----------------------------
create table if not exists fabric_supplier (
    id              bigint generated by default as identity,
    name            varchar(150) not null,
    phone           varchar(100),
    address         varchar(500),
    remarks         varchar(1000),
    create_time     datetime default current_timestamp,
    primary key (id),
    constraint uk_fabric_supplier_name unique (name)
);

create table if not exists fabric_category (
    id              bigint generated by default as identity,
    parent_id       bigint,
    name            varchar(100) not null,
    category_level  int not null,
    sort_order      int default 0,
    primary key (id),
    constraint uk_fabric_category unique (parent_id, name),
    index idx_fabric_category_parent (parent_id, sort_order)
);

create table if not exists fabric_component_type (
    code            varchar(8) not null,
    name_cn         varchar(100) not null,
    name_en         varchar(100) not null,
    sort_order      int default 0,
    enabled         char(1) default '1',
    primary key (code)
);

create table if not exists fabric (
    id                  bigint generated by default as identity,
    code                varchar(32) not null,
    entry_date          date not null,
    fabric_year         int not null,
    category_id         bigint not null,
    supplier_id         bigint not null,
    product_name        varchar(200) not null,
    weight              numeric(12,2) not null,
    width               numeric(12,2) not null,
    color_no            varchar(100),
    composition_code    varchar(8) not null,
    composition_summary varchar(500) not null,
    price_value         numeric(16,4) not null,
    price_unit          varchar(8) not null,
    meter_price         numeric(16,4),
    notes               varchar(2000),
    del_flag            char(1) default '0',
    create_by           varchar(64) default '',
    create_time         datetime default current_timestamp,
    update_by           varchar(64) default '',
    update_time         datetime,
    primary key (id),
    constraint uk_fabric_code unique (code),
    index idx_fabric_code_year (code, fabric_year),
    index idx_fabric_supplier_year (supplier_id, fabric_year),
    index idx_fabric_entry_date (entry_date)
);

create table if not exists fabric_composition (
    id              bigint generated by default as identity,
    fabric_id       bigint not null,
    component_code  varchar(8) not null,
    percentage      numeric(5,2) not null,
    sort_order      int default 0,
    primary key (id),
    constraint uk_fabric_composition unique (fabric_id, component_code),
    index idx_fabric_composition_fabric (fabric_id, sort_order)
);

create table if not exists fabric_image (
    id              bigint generated by default as identity,
    fabric_id       bigint not null,
    image_url       varchar(500) not null,
    thumbnail_url   varchar(500),
    image_type      varchar(32) default 'other',
    sort_order      int default 0,
    create_time     datetime default current_timestamp,
    primary key (id),
    index idx_fabric_image_fabric (fabric_id, sort_order)
);

-- 2026辅料使用独立档案和独立供应商，避免与面料供应商混用。
create table if not exists fabric_accessory_supplier (
    id              bigint generated by default as identity,
    name            varchar(150) not null,
    phone           varchar(100),
    address         varchar(500),
    create_time     datetime default current_timestamp,
    primary key (id),
    constraint uk_fabric_accessory_supplier_name unique (name)
);

create table if not exists fabric_accessory (
    id              bigint generated by default as identity,
    code            varchar(64) not null,
    entry_date      date,
    accessory_year  int not null default 2026,
    supplier_id     bigint not null,
    size_spec       varchar(200),
    bulk_price      varchar(200),
    regular_use     char(1),
    compliant       char(1),
    notes           varchar(1000),
    del_flag        char(1) default '0',
    create_by       varchar(64) default '',
    create_time     datetime default current_timestamp,
    update_by       varchar(64) default '',
    update_time     datetime,
    primary key (id),
    constraint uk_fabric_accessory_code unique (code),
    index idx_fabric_accessory_supplier (supplier_id),
    index idx_fabric_accessory_status (regular_use, compliant)
);

create table if not exists fabric_accessory_image (
    id              bigint generated by default as identity,
    accessory_id    bigint not null,
    image_url       varchar(500) not null,
    thumbnail_url   varchar(500),
    sort_order      int default 0,
    create_time     datetime default current_timestamp,
    primary key (id),
    index idx_fabric_accessory_image (accessory_id, sort_order)
);

-- 辅料供应商三项资料必须完整；旧测试数据统一补全，不再出现“待补充”。
update fabric_accessory_supplier
   set name = concat('辅料供应商-', id)
 where name is null
    or trim(name) = ''
    or name = '待补充供应商';
update fabric_accessory_supplier
   set phone = concat(
       '1380000',
       lpad(cast(mod(id, 10000) as varchar), 4, '0')
   )
 where phone is null or trim(phone) = '';
update fabric_accessory_supplier
   set address = concat('辅料供应商测试地址-', id)
 where address is null or trim(address) = '';
alter table fabric_accessory_supplier alter column phone set not null;
alter table fabric_accessory_supplier alter column address set not null;

-- 测试数据数量由初始化服务控制。启动脚本不得再硬删除档案、图片、供应商或成分，
-- 避免破坏库存、业务单据和历史流水所依赖的档案关系。

-- 年份页签只是界面筛选；真正优化年份查询的是以下组合索引。
create index if not exists idx_fabric_year_code
    on fabric(fabric_year, code);
create index if not exists idx_fabric_accessory_year_code
    on fabric_accessory(accessory_year, code);
create index if not exists idx_fabric_accessory_entry_date
    on fabric_accessory(entry_date);

-- 为已有辅料数据补填 entry_date（从 create_time 推导）。
update fabric_accessory
   set entry_date = cast(create_time as date)
 where entry_date is null;

-- 修复早期测试数据编辑后生成的错误缩略图路径。
update fabric_image
   set thumbnail_url = replace(
       thumbnail_url,
       '/profile/fabric/thumbnail/test/original/',
       '/profile/fabric/test/thumbnail/'
   )
 where thumbnail_url like '/profile/fabric/thumbnail/test/original/%';

create table if not exists fabric_code_sequence (
    fabric_year     int not null,
    last_value      int not null default 0,
    primary key (fabric_year)
);

create table if not exists fabric_accessory_code_sequence (
    accessory_year  int not null,
    last_value      int not null default 0,
    primary key (accessory_year)
);

-- 在应用开放请求前创建当年流水行，避免新年度首批并发请求竞争初始化。
insert into fabric_code_sequence (fabric_year, last_value)
select year(current_date), 0
 where not exists (
     select 1
       from fabric_code_sequence
      where fabric_year = year(current_date)
 );

-- 新编号格式取消年份与四位流水之间的连字符：A-26-0301-PO -> A-260301-PO。
update fabric
   set code = concat(substring(code, 1, 4), substring(code, 6))
 where code like 'A-__-____-%';

-- 修复早期允许修改成分、但未同步编号后缀的历史记录。
update fabric
   set code = regexp_replace(
       code,
       '-[^-]+$',
       concat('-', composition_code)
   )
 where code not like concat('%-', composition_code);
merge into fabric_code_sequence (fabric_year, last_value) key(fabric_year)
select fabric_year, max(cast(substring(code, 5, 4) as int))
  from fabric
 where code like 'A-______-%'
 group by fabric_year;

-- 辅料编号按年度独立连续编号：B- + 两位年份 + 四位流水号。
update fabric_accessory
   set code = concat('TMP-B-', id)
 where del_flag = '0';
update fabric_accessory current_accessory
   set code = concat(
       'B-',
       substring(cast(current_accessory.accessory_year as varchar), 3, 2),
       lpad(
           cast((
               select count(*)
                 from fabric_accessory previous_accessory
                where previous_accessory.del_flag = '0'
                  and previous_accessory.accessory_year =
                      current_accessory.accessory_year
                  and previous_accessory.id <= current_accessory.id
           ) as varchar),
           4,
           '0'
       )
   )
 where current_accessory.del_flag = '0';
merge into fabric_accessory_code_sequence (
    accessory_year, last_value
) key(accessory_year)
select accessory_year, count(*)
  from fabric_accessory
 where del_flag = '0'
 group by accessory_year;

-- 表单精度统一：金额两位小数，克重、包边门幅和成分比例均为整数。
update fabric
   set price_value = round(price_value, 2),
       meter_price = round(meter_price, 2),
       weight = round(weight, 0),
       width = round(width, 0);
update fabric_composition
   set percentage = round(percentage, 0);

-- 单一成分下拉字典；组合代码由系统根据多行成分自动推导。
merge into fabric_component_type key(code) values
('PO', '涤纶/聚酯', 'Polyester',          1, '1'),
('CO', '全棉',      'Cotton',             2, '1'),
('VI', '人丝/粘胶', 'Viscose',            3, '1'),
('SP', '氨纶',      'Spandex/Elastane',   4, '1'),
('LI', '亚麻',      'Linen',              5, '1'),
('PA', '尼龙',      'Polyamide/Nylon',    6, '1'),
('PU', '人造皮革',  'PU',                 7, '1'),
('OT', '其他',      'Other',              8, '1');

-- 《面料分类清单》定义的两级分类：3个一级大类、35个二级分类。
merge into fabric_category key(id) values
(1,   null, '梭织',       1, 1),
(2,   null, '针织',       1, 2),
(3,   null, '工艺面料',   1, 3),

(101, 1, '雪纺',         2, 1),
(102, 1, '牛仔',         2, 2),
(103, 1, '府绸',         2, 3),
(104, 1, '斜纹',         2, 4),
(105, 1, '缎面',         2, 5),
(106, 1, '欧根纱',       2, 6),
(107, 1, '乔其纱',       2, 7),
(108, 1, '人丝',         2, 8),
(109, 1, '醋酸',         2, 9),
(110, 1, '棉麻',         2, 10),
(111, 1, '亚麻',         2, 11),
(112, 1, '真丝',         2, 12),
(113, 1, '泡泡纱',       2, 13),
(114, 1, '乱麻',         2, 14),
(115, 1, '竹节布',       2, 15),
(116, 1, '灯芯绒',       2, 16),
(117, 1, '毛呢',         2, 17),

(201, 2, '卫衣布',       2, 1),
(202, 2, '罗马布',       2, 2),
(203, 2, '空气层',       2, 3),
(204, 2, '摇粒绒',       2, 4),
(205, 2, '汗布',         2, 5),
(206, 2, '螺纹',         2, 6),
(207, 2, '莫代尔面料',   2, 7),
(208, 2, '冰丝针织',     2, 8),

(301, 3, '绣花',         2, 1),
(302, 3, '印花',         2, 2),
(303, 3, '蕾丝',         2, 3),
(304, 3, '复合',         2, 4),
(305, 3, '压褶',         2, 5),
(306, 3, '植绒',         2, 6),
(307, 3, '麂皮绒',       2, 7),
(308, 3, '烫金',         2, 8),
(309, 3, '钉珠',         2, 9),
(310, 3, '提花',         2, 10);

-- 业务主数据完整性：禁止分类、面料、成分和图片产生无效关联。
alter table fabric_category
    add constraint if not exists fk_fabric_category_parent
    foreign key (parent_id) references fabric_category(id);
alter table fabric
    add constraint if not exists fk_fabric_category
    foreign key (category_id) references fabric_category(id);
alter table fabric
    add constraint if not exists fk_fabric_supplier
    foreign key (supplier_id) references fabric_supplier(id);
alter table fabric_composition
    add constraint if not exists fk_fabric_composition_fabric
    foreign key (fabric_id) references fabric(id) on delete cascade;
alter table fabric_composition
    add constraint if not exists fk_fabric_composition_component
    foreign key (component_code) references fabric_component_type(code);
alter table fabric_image
    add constraint if not exists fk_fabric_image_fabric
    foreign key (fabric_id) references fabric(id) on delete cascade;
alter table fabric_accessory
    add column if not exists entry_date date;
alter table fabric_accessory
    add constraint if not exists fk_fabric_accessory_supplier
    foreign key (supplier_id) references fabric_accessory_supplier(id);
alter table fabric_accessory_image
    add constraint if not exists fk_fabric_accessory_image
    foreign key (accessory_id) references fabric_accessory(id) on delete cascade;

-- 面料管理菜单（与系统管理同级）
merge into sys_menu key(menu_id) values('3000', '档案管理', '0',    '1', 'fabric', null,                  '', '', 1, 0, 'M', '0', '0', '',                     'shopping', 'admin', current_timestamp, '', null, '面辅料档案管理目录');
merge into sys_menu key(menu_id) values('3001', '面料档案', '3000', '1', 'list',   'fabric/index',        '', '', 1, 0, 'C', '0', '0', 'fabric:fabric:list', 'list',     'admin', current_timestamp, '', null, '面料档案菜单');
merge into sys_menu key(menu_id) values('3010', '辅料档案', '3000', '2', 'accessory', 'fabric/index', '{"type":"accessory"}', '', 1, 0, 'C', '0', '0', 'fabric:fabric:list', 'list', 'admin', current_timestamp, '', null, '辅料档案菜单');
merge into sys_menu key(menu_id) values('3008', '基础资料', '3000', '3', 'master', 'fabric/master',       '', '', 1, 0, 'C', '0', '0', 'fabric:master:list',  'tree-table','admin', current_timestamp, '', null, '分类和供应商维护');
merge into sys_menu key(menu_id) values('3002', '面料查询', '3001', '1', '',       '',                    '', '', 1, 0, 'F', '0', '0', 'fabric:fabric:query', '#',        'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('3003', '面料新增', '3001', '2', '',       '',                    '', '', 1, 0, 'F', '0', '0', 'fabric:fabric:add',   '#',        'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('3004', '面料修改', '3001', '3', '',       '',                    '', '', 1, 0, 'F', '0', '0', 'fabric:fabric:edit',  '#',        'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('3005', '面料删除', '3001', '4', '',       '',                    '', '', 1, 0, 'F', '0', '0', 'fabric:fabric:remove','#',        'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('3007', '图片上传', '3001', '6', '',       '',                    '', '', 1, 0, 'F', '0', '0', 'fabric:fabric:upload','#',        'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('3009', '基础资料维护', '3008', '1', '',    '',                    '', '', 1, 0, 'F', '0', '0', 'fabric:master:edit',  '#',        'admin', current_timestamp, '', null, '');

-- 清理已取消的面料导入权限，并初始化面料专用角色的最小权限集
delete from sys_role_menu where menu_id = 3006;
delete from sys_menu where menu_id = 3006;

-- 面料主管：查询、新增、修改、删除和图片上传
merge into sys_role_menu key(role_id, menu_id) values ('3', '3000');
merge into sys_role_menu key(role_id, menu_id) values ('3', '3001');
merge into sys_role_menu key(role_id, menu_id) values ('3', '3002');
merge into sys_role_menu key(role_id, menu_id) values ('3', '3003');
merge into sys_role_menu key(role_id, menu_id) values ('3', '3004');
merge into sys_role_menu key(role_id, menu_id) values ('3', '3005');
merge into sys_role_menu key(role_id, menu_id) values ('3', '3007');
merge into sys_role_menu key(role_id, menu_id) values ('3', '3008');
merge into sys_role_menu key(role_id, menu_id) values ('3', '3009');
merge into sys_role_menu key(role_id, menu_id) values ('3', '3010');

-- 面料录入员：查询、新增、修改本人数据和图片上传
merge into sys_role_menu key(role_id, menu_id) values ('4', '3000');
merge into sys_role_menu key(role_id, menu_id) values ('4', '3001');
merge into sys_role_menu key(role_id, menu_id) values ('4', '3002');
merge into sys_role_menu key(role_id, menu_id) values ('4', '3003');
merge into sys_role_menu key(role_id, menu_id) values ('4', '3004');
merge into sys_role_menu key(role_id, menu_id) values ('4', '3007');
merge into sys_role_menu key(role_id, menu_id) values ('4', '3010');

-- 面料查询员：只允许查看列表和详情
merge into sys_role_menu key(role_id, menu_id) values ('5', '3000');
merge into sys_role_menu key(role_id, menu_id) values ('5', '3001');
merge into sys_role_menu key(role_id, menu_id) values ('5', '3002');
merge into sys_role_menu key(role_id, menu_id) values ('5', '3010');

-- ----------------------------
-- 面辅料库存管理
-- ----------------------------
create table if not exists inventory_stock (
    id                       bigint generated by default as identity,
    stock_code               varchar(30) not null,
    material_type            char(1) not null,
    fabric_id                bigint default null,
    accessory_id             bigint default null,
    material_code            varchar(80) default null,
    development_style_no     varchar(100) default null,
    skc                      varchar(100) default null,
    color_no                 varchar(100) default null,
    goods_type               varchar(100) default null,
    primary_unit             varchar(20) not null,
    auxiliary_unit           varchar(20) default null,
    on_hand_qty              decimal(18,3) not null default 0,
    locked_qty               decimal(18,3) not null default 0,
    on_hand_aux_qty          decimal(18,3) not null default 0,
    locked_aux_qty           decimal(18,3) not null default 0,
    last_count_time          datetime default null,
    version                  int not null default 0,
    source_key               varchar(150) default null,
    del_flag                 char(1) not null default '0',
    create_by                varchar(64) default '',
    create_time              datetime,
    update_by                varchar(64) default '',
    update_time              datetime,
    remark                   varchar(1000) default null,
    primary key (id),
    constraint uk_inventory_stock_code unique (stock_code),
    constraint uk_inventory_stock_source unique (source_key),
    index idx_inventory_stock_archive (material_type, fabric_id, accessory_id),
    index idx_inventory_stock_material (material_code),
    index idx_inventory_stock_style (development_style_no),
    index idx_inventory_stock_count_time (last_count_time)
);

create table if not exists inventory_stock_image (
    id              bigint generated by default as identity,
    stock_id        bigint not null,
    image_url       varchar(500) not null,
    thumbnail_url   varchar(500) default null,
    image_type      varchar(20) not null default 'material',
    source_name     varchar(500) default null,
    content_hash    varchar(64) default null,
    sort_order      int not null default 0,
    create_time     datetime,
    primary key (id),
    index idx_inventory_stock_image (stock_id, sort_order)
);

create table if not exists inventory_inbound_order (
    id              bigint generated by default as identity,
    order_no        varchar(30) not null,
    order_date      date not null,
    status          varchar(20) not null default 'DRAFT',
    operator_name   varchar(100) default null,
    create_by       varchar(64) default '',
    create_time     datetime,
    update_by       varchar(64) default '',
    update_time     datetime,
    remark          varchar(1000) default null,
    primary key (id),
    constraint uk_inventory_inbound_no unique (order_no),
    index idx_inventory_inbound_date (order_date, status)
);

create table if not exists inventory_inbound_detail (
    id                  bigint generated by default as identity,
    order_id            bigint not null,
    stock_id            bigint not null,
    quantity            decimal(18,3) not null,
    auxiliary_quantity  decimal(18,3) not null default 0,
    sort_order          int not null default 0,
    primary key (id),
    index idx_inventory_inbound_detail (order_id, sort_order),
    index idx_inventory_inbound_stock (stock_id)
);

create table if not exists inventory_requisition_order (
    id                    bigint generated by default as identity,
    order_no              varchar(30) not null,
    order_date            date not null,
    applicant_name        varchar(100) not null,
    development_style_no  varchar(100) default null,
    status                varchar(20) not null default 'DRAFT',
    create_by             varchar(64) default '',
    create_time           datetime,
    update_by             varchar(64) default '',
    update_time           datetime,
    remark                varchar(1000) default null,
    primary key (id),
    constraint uk_inventory_requisition_no unique (order_no),
    index idx_inventory_requisition_date (order_date, status),
    index idx_inventory_requisition_applicant (applicant_name)
);

create table if not exists inventory_requisition_detail (
    id                  bigint generated by default as identity,
    order_id            bigint not null,
    stock_id            bigint not null,
    quantity            decimal(18,3) not null,
    auxiliary_quantity  decimal(18,3) not null default 0,
    sort_order          int not null default 0,
    primary key (id),
    index idx_inventory_requisition_detail (order_id, sort_order),
    index idx_inventory_requisition_stock (stock_id)
);

create table if not exists inventory_movement (
    id                           bigint generated by default as identity,
    movement_no                  varchar(35) not null,
    stock_id                     bigint not null,
    movement_type                varchar(30) not null,
    business_type                varchar(30) not null,
    business_id                  bigint default null,
    business_no                  varchar(30) default null,
    quantity_change              decimal(18,3) not null default 0,
    locked_change                decimal(18,3) not null default 0,
    auxiliary_change             decimal(18,3) not null default 0,
    locked_auxiliary_change      decimal(18,3) not null default 0,
    balance_qty                  decimal(18,3) not null,
    balance_locked_qty           decimal(18,3) not null,
    balance_aux_qty              decimal(18,3) not null,
    balance_locked_aux_qty       decimal(18,3) not null,
    operator_name                varchar(100) not null,
    operation_time               datetime not null,
    remark                       varchar(1000) default null,
    primary key (id),
    constraint uk_inventory_movement_no unique (movement_no),
    index idx_inventory_movement_stock (stock_id, operation_time),
    index idx_inventory_movement_business (business_type, business_id),
    index idx_inventory_movement_time (operation_time)
);

create table if not exists inventory_code_sequence (
    sequence_type   varchar(20) not null,
    sequence_date   varchar(10) not null,
    last_value      int not null default 0,
    primary key (sequence_type, sequence_date)
);

alter table inventory_stock
    add constraint if not exists fk_inventory_stock_fabric
    foreign key (fabric_id) references fabric(id);
alter table inventory_stock
    add constraint if not exists fk_inventory_stock_accessory
    foreign key (accessory_id) references fabric_accessory(id);
alter table inventory_stock_image
    add constraint if not exists fk_inventory_stock_image
    foreign key (stock_id) references inventory_stock(id) on delete cascade;
alter table inventory_inbound_detail
    add constraint if not exists fk_inventory_inbound_detail_order
    foreign key (order_id) references inventory_inbound_order(id) on delete cascade;
alter table inventory_inbound_detail
    add constraint if not exists fk_inventory_inbound_detail_stock
    foreign key (stock_id) references inventory_stock(id);
alter table inventory_requisition_detail
    add constraint if not exists fk_inventory_requisition_detail_order
    foreign key (order_id) references inventory_requisition_order(id) on delete cascade;
alter table inventory_requisition_detail
    add constraint if not exists fk_inventory_requisition_detail_stock
    foreign key (stock_id) references inventory_stock(id);
alter table inventory_movement
    add constraint if not exists fk_inventory_movement_stock
    foreign key (stock_id) references inventory_stock(id);

-- 修复旧版本中“库存仍有效但关联档案已被软删除”的历史不一致。
update fabric set del_flag='0'
 where id in (
     select fabric_id from inventory_stock
      where del_flag='0' and fabric_id is not null
 );
update fabric_accessory set del_flag='0'
 where id in (
     select accessory_id from inventory_stock
      where del_flag='0' and accessory_id is not null
 );

-- 数据库层最后防线：类型、关联字段、余额、单据数量和状态必须自洽。
alter table inventory_stock
    add constraint if not exists ck_inventory_stock_material_type
    check (material_type in ('F','A'));
alter table inventory_stock
    add constraint if not exists ck_inventory_stock_archive_type
    check ((material_type='F' and accessory_id is null)
        or (material_type='A' and fabric_id is null));
alter table inventory_stock
    add constraint if not exists ck_inventory_stock_balance
    check (on_hand_qty >= 0 and locked_qty >= 0 and locked_qty <= on_hand_qty
       and on_hand_aux_qty >= 0 and locked_aux_qty >= 0
       and locked_aux_qty <= on_hand_aux_qty);
alter table inventory_inbound_order
    add constraint if not exists ck_inventory_inbound_status
    check (status in ('DRAFT','POSTED','CANCELED'));
alter table inventory_inbound_detail
    add constraint if not exists ck_inventory_inbound_quantity
    check (quantity > 0 and auxiliary_quantity >= 0);
alter table inventory_requisition_order
    add constraint if not exists ck_inventory_requisition_status
    check (status in ('DRAFT','LOCKED','ISSUED','CANCELED','RETURNED'));
alter table inventory_requisition_detail
    add constraint if not exists ck_inventory_requisition_quantity
    check (quantity > 0 and auxiliary_quantity >= 0);
alter table inventory_movement
    add constraint if not exists ck_inventory_movement_balance
    check (balance_qty >= 0 and balance_locked_qty >= 0
       and balance_locked_qty <= balance_qty and balance_aux_qty >= 0
       and balance_locked_aux_qty >= 0
       and balance_locked_aux_qty <= balance_aux_qty);

-- Excel 嵌入层会将原始 JPG/PNG 统一封装，期初图片先按物料实物图归档，后续可人工调整类型。
update inventory_stock_image set image_type = 'material'
 where source_name like 'row-%';

-- 库存管理菜单及按钮权限
merge into sys_menu key(menu_id) values('4000', '库存管理', '0',    '2', 'inventory',    null,                              '', '', 1, 0, 'M', '0', '0', '',                           'component', 'admin', current_timestamp, '', null, '面辅料库存管理目录');
merge into sys_menu key(menu_id) values('4001', '库存台账', '4000', '1', 'stock',        'inventory/stock/index',           '', '', 1, 0, 'C', '0', '0', 'inventory:stock:list',       'table',     'admin', current_timestamp, '', null, '库存台账菜单');
merge into sys_menu key(menu_id) values('4002', '入库单',   '4000', '2', 'inbound',      'inventory/inbound/index',         '', '', 1, 0, 'C', '0', '0', 'inventory:inbound:list',     'download',  'admin', current_timestamp, '', null, '入库单菜单');
merge into sys_menu key(menu_id) values('4003', '领用单',   '4000', '3', 'requisition',  'inventory/requisition/index',     '', '', 1, 0, 'C', '0', '0', 'inventory:requisition:list', 'upload',    'admin', current_timestamp, '', null, '领用单菜单');
merge into sys_menu key(menu_id) values('4004', '库存流水', '4000', '4', 'movement',     'inventory/movement/index',        '', '', 1, 0, 'C', '0', '0', 'inventory:movement:list',    'list',      'admin', current_timestamp, '', null, '库存流水菜单');

merge into sys_menu key(menu_id) values('4010', '库存查询', '4001', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:stock:query', '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4011', '库存新增', '4001', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:stock:add',   '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4012', '库存修改', '4001', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:stock:edit',  '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4013', '库存调整', '4001', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:stock:adjust','#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4014', '库存删除', '4001', '5', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:stock:remove','#', 'admin', current_timestamp, '', null, '仅允许删除零余额且无单据流水的误建库存行');
merge into sys_menu key(menu_id) values('4020', '入库查询', '4002', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:inbound:query', '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4021', '入库新增', '4002', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:inbound:add',   '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4022', '入库修改', '4002', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:inbound:edit',  '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4023', '入库删除', '4002', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:inbound:remove','#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4024', '入库过账', '4002', '5', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:inbound:post',   '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4025', '入库冲销', '4002', '6', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:inbound:cancel', '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4030', '领用查询', '4003', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:requisition:query', '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4031', '领用新增', '4003', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:requisition:add',   '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4032', '领用修改', '4003', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:requisition:edit',  '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4033', '领用删除', '4003', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:requisition:remove','#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4034', '库存锁定', '4003', '5', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:requisition:lock',  '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4035', '领用发料', '4003', '6', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:requisition:issue', '#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4036', '领用取消', '4003', '7', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:requisition:cancel','#', 'admin', current_timestamp, '', null, '');
merge into sys_menu key(menu_id) values('4037', '领用退回', '4003', '8', '', '', '', '', 1, 0, 'F', '0', '0', 'inventory:requisition:return','#', 'admin', current_timestamp, '', null, '');

-- 库存主管拥有全部库存权限
insert into sys_role_menu (role_id, menu_id)
select 3, menu_id from sys_menu where menu_id between 4000 and 4037
and not exists (select 1 from sys_role_menu rm where rm.role_id = 3 and rm.menu_id = sys_menu.menu_id);
-- 录入员可维护草稿并执行日常过账、锁定和发料，不允许库存调整、入库冲销及已发料退回
insert into sys_role_menu (role_id, menu_id)
select 4, menu_id from sys_menu
where menu_id between 4000 and 4037 and menu_id not in (4013, 4014, 4025, 4037)
and not exists (select 1 from sys_role_menu rm where rm.role_id = 4 and rm.menu_id = sys_menu.menu_id);
-- 查询员只查看四类列表和详情
insert into sys_role_menu (role_id, menu_id)
select 5, menu_id from sys_menu where menu_id in (4000,4001,4002,4003,4004,4010,4020,4030)
and not exists (select 1 from sys_role_menu rm where rm.role_id = 5 and rm.menu_id = sys_menu.menu_id);

-- 使用帮助对所有预置角色开放。
merge into sys_role_menu key(role_id, menu_id) values ('2', '4');
merge into sys_role_menu key(role_id, menu_id) values ('3', '4');
merge into sys_role_menu key(role_id, menu_id) values ('4', '4');
merge into sys_role_menu key(role_id, menu_id) values ('5', '4');

commit;
