<template>
  <div class="app-container order-page">
    <section class="order-head"><div><span>MATERIAL ISSUE</span><h2>领用单</h2><p>先锁定、后发料；取消锁定和发料退回均保留完整流水。</p></div><el-button type="primary" icon="Plus" @click="openAdd" v-hasPermi="['inventory:requisition:add']">新建领用单</el-button></section>
    <el-form ref="queryRef" :model="query" inline><el-form-item label="单号" prop="orderNo"><el-input v-model="query.orderNo" clearable /></el-form-item><el-form-item label="领用人" prop="applicantName"><el-input v-model="query.applicantName" clearable /></el-form-item><el-form-item label="状态" prop="status"><el-select v-model="query.status" clearable style="width:140px"><el-option v-for="item in statuses" :key="item.value" :label="item.label" :value="item.value"/></el-select></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="search">查询</el-button><el-button icon="Refresh" @click="resetQuery">重置</el-button></el-form-item></el-form>
    <el-table v-loading="loading" :data="rows"><el-table-column label="领用单号" prop="orderNo" min-width="180"/><el-table-column label="日期" prop="orderDate" width="115"/><el-table-column label="领用人" prop="applicantName" min-width="110"/><el-table-column label="开发款号" prop="developmentStyleNo" min-width="125"/><el-table-column label="状态" width="100" align="center"><template #default="{row}"><el-tag :type="statusType(row.status)">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column label="录入员" prop="createBy" min-width="105"/><el-table-column label="备注" prop="remark" min-width="160" show-overflow-tooltip/><el-table-column label="操作" width="305" fixed="right" align="center"><template #default="{row}"><el-button link type="primary" @click="view(row)">查看</el-button><el-button v-if="row.status==='DRAFT'" link type="primary" @click="edit(row)" v-hasPermi="['inventory:requisition:edit']">修改</el-button><el-button v-if="row.status==='DRAFT'" link type="success" @click="lock(row)" v-hasPermi="['inventory:requisition:lock']">锁定</el-button><el-button v-if="row.status==='LOCKED'" link type="success" @click="issue(row)" v-hasPermi="['inventory:requisition:issue']">发料</el-button><el-button v-if="['DRAFT','LOCKED'].includes(row.status)" link type="warning" @click="cancel(row)" v-hasPermi="['inventory:requisition:cancel']">取消</el-button><el-button v-if="row.status==='DRAFT'" link type="danger" @click="remove(row)" v-hasPermi="['inventory:requisition:remove']">删除</el-button><el-button v-if="row.status==='ISSUED'" link type="warning" @click="returnOrder(row)" v-hasPermi="['inventory:requisition:return']">退回</el-button></template></el-table-column></el-table>
    <pagination v-show="total>0" :total="total" v-model:page="query.pageNum" v-model:limit="query.pageSize" @pagination="load"/>

    <el-dialog v-model="open" :title="readonly?'领用单详情':(form.id?'修改领用单':'新建领用单')" width="1050px" append-to-body :close-on-click-modal="false">
      <el-form ref="formRef" :model="form" :rules="rules" label-width="88px"><el-row :gutter="18"><el-col :span="6"><el-form-item label="领用单号"><el-input :model-value="form.orderNo||'保存后生成'" disabled/></el-form-item></el-col><el-col :span="6"><el-form-item label="日期" prop="orderDate"><el-date-picker v-model="form.orderDate" type="date" value-format="YYYY-MM-DD" :disabled="readonly" style="width:100%"/></el-form-item></el-col><el-col :span="6"><el-form-item label="领用人" prop="applicantName"><el-input v-model="form.applicantName" :disabled="readonly"/></el-form-item></el-col><el-col :span="6"><el-form-item label="开发款号"><el-input v-model="form.developmentStyleNo" :disabled="readonly"/></el-form-item></el-col></el-row>
      <div class="detail-title"><strong>领用明细</strong><el-button v-if="!readonly" type="primary" plain icon="Plus" @click="addDetail">添加明细</el-button></div>
      <el-table :data="form.details" border><el-table-column label="库存行" min-width="300"><template #default="{row}"><el-select v-model="row.stockId" filterable :disabled="readonly" style="width:100%"><el-option v-for="item in stocks" :key="item.id" :label="stockLabel(item)" :value="item.id"/></el-select></template></el-table-column><el-table-column label="领用数量" width="180"><template #default="{row}"><el-input-number v-model="row.quantity" :min="0.001" :precision="3" :disabled="readonly" style="width:100%"/><span class="unit">{{ unit(row.stockId,'primaryUnit') }}</span></template></el-table-column><el-table-column label="辅助数量" width="180"><template #default="{row}"><el-input-number v-model="row.auxiliaryQuantity" :min="0" :precision="3" :disabled="readonly" style="width:100%"/><span class="unit">{{ unit(row.stockId,'auxiliaryUnit') }}</span></template></el-table-column><el-table-column v-if="!readonly" label="操作" width="70" align="center"><template #default="{$index}"><el-button link type="danger" icon="Delete" @click="form.details.splice($index,1)"/></template></el-table-column></el-table>
      <el-form-item label="备注" class="remark"><el-input v-model="form.remark" type="textarea" :rows="3" :disabled="readonly"/></el-form-item></el-form>
      <template #footer><el-button v-if="!readonly" type="primary" :loading="saving" @click="submit">保存草稿</el-button><el-button @click="open=false">关闭</el-button></template>
    </el-dialog>
  </div>
</template>

<script setup>
import {listRequisition,getRequisition,addRequisition,updateRequisition,deleteRequisition,lockRequisition,issueRequisition,cancelRequisition,returnRequisition,listStocks} from "@/api/inventory/inventory"
const {proxy}=getCurrentInstance();const loading=ref(false),saving=ref(false),open=ref(false),readonly=ref(false),rows=ref([]),stocks=ref([]),total=ref(0)
const query=reactive({pageNum:1,pageSize:20,orderNo:undefined,applicantName:undefined,status:undefined}),form=reactive({})
const statuses=[{value:'DRAFT',label:'草稿'},{value:'LOCKED',label:'已锁定'},{value:'ISSUED',label:'已发料'},{value:'CANCELED',label:'已取消'},{value:'RETURNED',label:'已退回'}]
const rules={orderDate:[{required:true,message:'请选择日期',trigger:'change'}],applicantName:[{required:true,message:'请输入领用人',trigger:'blur'}]}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function reset(){Object.assign(form,{id:undefined,orderNo:undefined,orderDate:today(),applicantName:'',developmentStyleNo:'',remark:'',details:[{stockId:undefined,quantity:1,auxiliaryQuantity:0}]})}
function load(){loading.value=true;listRequisition(query).then(r=>{rows.value=r.rows||[];total.value=r.total||0}).finally(()=>loading.value=false)} function loadStocks(){listStocks({pageNum:1,pageSize:1000}).then(r=>stocks.value=r.rows||[])} function search(){query.pageNum=1;load()} function resetQuery(){proxy.resetForm('queryRef');search()}
function openAdd(){reset();readonly.value=false;open.value=true} function edit(row){getRequisition(row.id).then(r=>{reset();Object.assign(form,r.data);readonly.value=false;open.value=true})} function view(row){getRequisition(row.id).then(r=>{reset();Object.assign(form,r.data);readonly.value=true;open.value=true})} function addDetail(){form.details.push({stockId:undefined,quantity:1,auxiliaryQuantity:0})}
function submit(){if(!form.details.length)return proxy.$modal.msgError('请添加领用明细');proxy.$refs.formRef.validate(valid=>{if(!valid)return;saving.value=true;(form.id?updateRequisition(form):addRequisition(form)).then(()=>{proxy.$modal.msgSuccess('领用单草稿已保存');open.value=false;load()}).finally(()=>saving.value=false)})}
function lock(row){proxy.$modal.confirm(`锁定 ${row.orderNo} 所需库存？`).then(()=>lockRequisition(row.id)).then(()=>{proxy.$modal.msgSuccess('库存锁定成功');load();loadStocks()}).catch(()=>{})}
function issue(row){proxy.$modal.confirm(`确认 ${row.orderNo} 已实际发料？该操作将扣减库存。`).then(()=>issueRequisition(row.id)).then(()=>{proxy.$modal.msgSuccess('发料成功');load();loadStocks()}).catch(()=>{})}
function cancel(row){proxy.$modal.confirm(`确认取消 ${row.orderNo}？已锁定库存将自动释放。`).then(()=>cancelRequisition(row.id)).then(()=>{proxy.$modal.msgSuccess('领用单已取消');load();loadStocks()}).catch(()=>{})}
function returnOrder(row){proxy.$modal.confirm(`确认 ${row.orderNo} 全部退回库存？`).then(()=>returnRequisition(row.id)).then(()=>{proxy.$modal.msgSuccess('退回成功');load();loadStocks()}).catch(()=>{})}
function remove(row){proxy.$modal.confirm(`确认删除草稿 ${row.orderNo}？`).then(()=>deleteRequisition(row.id)).then(()=>{proxy.$modal.msgSuccess('删除成功');load()}).catch(()=>{})}
function statusLabel(v){return statuses.find(i=>i.value===v)?.label||v} function statusType(v){return v==='ISSUED'?'success':v==='LOCKED'?'primary':v==='DRAFT'?'warning':'info'}
function stock(v){return stocks.value.find(i=>i.id===v)||{}} function unit(id,key){return stock(id)[key]||''} function stockLabel(i){return `${i.stockCode}｜${i.materialCode||'未编号'}｜${i.colorNo||'无色号'}｜可用 ${Number(i.onHandQty)-Number(i.lockedQty)} ${i.primaryUnit}`}
load();loadStocks()
</script>

<style scoped>
.order-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;padding:22px 26px;border:1px solid #ccfbf1;border-radius:12px;background:#f0fdfa}.order-head span{font-size:11px;letter-spacing:2px;color:#0f766e}.order-head h2{margin:4px 0}.order-head p{margin:0;color:#64748b}.detail-title{display:flex;justify-content:space-between;align-items:center;margin:8px 0 12px}.unit{display:block;margin-top:3px;color:#64748b;font-size:12px;text-align:right}.remark{margin-top:18px}:deep(.el-table__header th){background:#f8fafc}
</style>
